//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad
    {
        public int id { get; set; }
        public string ad_title { get; set; }
        public string ad_description { get; set; }
        public System.DateTime ad_post_date { get; set; }
        public int id_user { get; set; }
        public int id_city { get; set; }
        public int id_category { get; set; }
        public int id_type { get; set; }
        public int id_status { get; set; }
        public int ad_price { get; set; }
        public string ad_images { get; set; }
    
        public virtual category category { get; set; }
        public virtual city city { get; set; }
        public virtual status status { get; set; }
        public virtual type type { get; set; }
        public virtual user user { get; set; }
    }
}
